### PR TITLE
Use last completed automatic backup time instead of last available ba…

### LINKED ISSUE #23483: Backups - manually deleting most recent automatic backup shows false "backup failed" error card
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

If you manually delete the most recent automatic backup and then return to your backup panel, it will say that "Last automatic backup failed"  and that it "wasn't successful" even though that's not true. The backup doesn't exist but in this case it was a manual delete action performed by the user and NOT a failed backup.

https://github.com/user-attachments/assets/a0f7d7d4-6490-4ee8-9657-851b2fed5bcd

### Describe the behavior you expected

Don't show backup failed when the user manually deletes a backup

### Steps to reproduce the issue

See screen recording above, but:

1. Create an automatic backup
2. Click into "My backups" and delete the most recent backup
3. After returning to the main backup page, it will say "Last automatic backup failed"  and that it "wasn't successful"

### What version of Home Assistant Core has the issue?

2025.1.0b2

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

_No response_

### Which operating system are you using to run this browser?

_No response_

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### LINKED ISSUE #23519: BackUp Panel > Wrong data display if not fully loaded
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

The backup panel is working correct if my network connection is fine. However I have noted some strange behaviour if not (I assume it is due to the (internet) connection, cannot explain it otherwise). 

Although automatic backup is configured I get often this screen on my mobile phone:

image
sometimes this (but very rare)
image
and sometimes the correct one: 
image

My assumption is this that the first screenshot being the default page. If data cannot be loaded the default page stays displayed.

### Describe the behavior you expected

I would expect a loading circle as default unless data are not loaded. Having the initial backup screen as default is misleading information and not correct. Loading circles as default are also shown on other pages. 

### Steps to reproduce the issue

1. Configure backup
2. Force a slow / unstable external connection via VPN
3. Open BackUp page
...

### What version of Home Assistant Core has the issue?

core-2025.1.0b4

### What was the last working version of Home Assistant Core?

N/A

### In which browser are you experiencing the issue with?

Chrome 131.0.6778.200

### Which operating system are you using to run this browser?

Android 

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by bramkragten**
…ckup

Fixes https://github.com/home-assistant/frontend/issues/23483
Fixes https://github.com/home-assistant/frontend/issues/23519

## Type of change

- [ ] Dependency upgrade
- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/panels/config/backup/components/overview/ha-backup-overview-summary.ts [hunk 1]
```diff
@@ -84,22 +84,22 @@ class HaBackupOverviewBackups extends LitElement {
...
 
     const lastBackupDescription = lastSuccessfulBackup
-      ? `Last successful backup ${relativeTime(lastSuccessfulBackupDate, this.hass.locale, now, true)} and stored in ${lastSuccessfulBackup.agent_ids?.length} locations.`
+      ? `Last successful backup ${relativeTime(new Date(lastSuccessfulBackup.date), this.hass.locale, now, true)} and stored in ${lastSuccessfulBackup.agent_ids?.length} locations.`
       : "You have no successful backups.";
 
-    if (lastAttempt && lastAttempt > lastSuccessfulBackupDate) {
-      const lastAttemptDescription = `The last automatic backup triggered ${relativeTime(lastAttempt, this.hass.locale, now, true)} wasn't successful.`;
+    if (lastAttempt && lastAttempt > (lastCompletedBackupDate || 0)) {
+      const lastAttemptDescription = `The last automatic backup trigged ${relativeTime(lastAttempt, this.hass.locale, now, true)} wasn't successful.`;
```
Comment (silamon) [inline src/panels/config/backup/components/overview/ha-backup-overview-summary.ts:102]:
```suggestion
      const lastAttemptDescription = `The last automatic backup triggered ${relativeTime(lastAttempt, this.hass.locale, now, true)} wasn't successful.`;
```

**Review by frenck — APPROVED** [review]
