### PR TITLE
Fix location icon when many locations in backup datatable

### LINKED ISSUE #23952: Backup location icons stop at 3
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [x] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Hello,

Wanted to mention this, but when on my  
Android phone and switching between landscape and portrait mode I noticed that it doesn't show the fourth location where in the backups are, for example:

Image

Image

Minor thing I noticed on HA Core 2025.2.0b1

### Describe the behavior you expected

No missing icons 

### Steps to reproduce the issue

1.update to latest
2. Rotate phone on back up page
3.
...

### What version of Home Assistant Core has the issue?

2025.2.0b1

### What was the last working version of Home Assistant Core?

Not sure

### In which browser are you experiencing the issue?

Android app

### Which operating system are you using to run this browser?

_No response_

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml

```

### Javascript errors shown in your browser console/inspector

```txt

```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by piitaya**
## Proposed change

A maximum number of icons for locations will be displayed in the backup table. If there are more than the max, a number will be displayed.
The max is set to 3 or mobile and 5 on desktop.

CleanShot 2025-01-30 at 14 39 41

CleanShot 2025-01-30 at 14 39 31

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes https://github.com/home-assistant/frontend/issues/23952
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/panels/config/backup/ha-config-backup-backups.ts [hunk 1]
```diff
@@ -172,54 +175,75 @@ class HaConfigBackupBackups extends SubscribeMixin(LitElement) {
...
-                `;
-              }
-              if (isNetworkMountAgent(agentId)) {
+        // 24 icon size, 4 gap, 16 left and right padding
+        minWidth: `${maxAgents * 24 + (maxAgents - 1) * 4 + 32}px`,
+        template: (backup) => {
+          const agentIds = [...backup.agent_ids];
+          const displayedAgentIds =
+            agentIds.length > maxAgents
+              ? [...agentIds].splice(0, maxAgents - 1)
```
Comment (bramkragten) [inline src/panels/config/backup/ha-config-backup-backups.ts:184]: And then we make a copy here again?

File: src/panels/config/backup/ha-config-backup-backups.ts [hunk 2]
```diff
@@ -172,54 +175,75 @@ class HaConfigBackupBackups extends SubscribeMixin(LitElement) {
...
-              }
-              if (isNetworkMountAgent(agentId)) {
+        // 24 icon size, 4 gap, 16 left and right padding
+        minWidth: `${maxAgents * 24 + (maxAgents - 1) * 4 + 32}px`,
+        template: (backup) => {
+          const agentIds = backup.agent_ids;
+          const displayedAgentIds =
+            agentIds.length > maxAgents
+              ? [...agentIds].splice(0, maxAgents - 1)
+              : agentIds;
```
Comment (bramkragten) [inline src/panels/config/backup/ha-config-backup-backups.ts:185]: Can `agentIds` be undefined now? As in the old code we had `backup.agent_ids || []`

**Review by bramkragten — APPROVED** [review]
