### PR TITLE
fix ha-textfield (max-width, text-overflow, padding)

### LINKED ISSUE #23193: Unneeded scrollbar in card-config
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Consider an Entities card:
image

The scrollbar is not needed.
Probably comes from here:
https://github.com/home-assistant/frontend/blob/df21900341f8ef714e22352d9cbb794d4981e8e2/src/panels/lovelace/editor/config-elements/config-elements-style.ts#L6

### Describe the behavior you expected

Scrollbar is shown when it is needed.

### Steps to reproduce the issue

see above

### What version of Home Assistant Core has the issue?

2024.12

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

Chrome 131.0.6778.86 

### Which operating system are you using to run this browser?

Win10x64

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by ildar170975**
## Proposed change

Fixed `max-width` for "label" element which caused overflow in Entities card editor (similar - in a graph footer/header editor).
Before:
image

After:
image

Also, fixed a right padding & `text-overflow`. Along with `max-width` fix, now a long "label" looks better.
Before:
image

After:
image

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes https://github.com/home-assistant/frontend/issues/23193
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/components/ha-textfield.ts [hunk 1]
```diff
@@ -136,13 +136,12 @@ export class HaTextField extends TextFieldBase {
...
-        padding-right: 30px;
-        padding-inline-end: 30px;
-        padding-inline-start: initial;
-        box-sizing: border-box;
-        direction: var(--direction);
+        max-width: calc(100% - 16px);
+      }
+
+      .mdc-floating-label--float-above {
+        max-width: calc((100% - 16px) / 0.75);
```
Comment (MindFreeze) [inline src/components/ha-textfield.ts:143]: I don't understand. Why `/ 0.75` ?

Comment (ildar170975) [reply src/components/ha-textfield.ts:143]: xx-above uses a scale 0.75 in "transform".
That is why a width is increased to get a "still same size" effect.

**Review by MindFreeze — APPROVED** [review]
