### PR TITLE
Fix more-info chart rendering

### LINKED ISSUE #23584: More-info dialog is slow and laggy after update to 2025.1.0
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

After updating to 2025.1.0, graphs that are opened from an entity on the dashboard, for example a temperature or humidity graph, are an unpleasant experience.
The opened graph lags, flashes and redraws multiple times over 1-2 seconds until it has reached the end of its opening animation and its final size.

Checked in Chromium 131 and Firefox 133 on Thinkpad X1 Yoga Gen7.

### Describe the behavior you expected

Graphs should open like before 2025.1.0, no animation and in less than 500ms, or better less than 300ms.

### Steps to reproduce the issue

1. Update to 2025.1.0
2. (maybe optional) Use laptop with 4k screen and Intel Xe graphics.
3. Enjoy the laggy web UI after clicking on a temperature entity on your dashboard to see the graph.

### What version of Home Assistant Core has the issue?

2025.1.0

### What was the last working version of Home Assistant Core?

2024.12.1

### In which browser are you experiencing the issue with?

Chromium 131, Firefox 133

### Which operating system are you using to run this browser?

Debian Linux Unstable

### State of relevant entities

```txt
Entities are displayed fine, dashboard is fine, pop-up graph is laggy and slow.
See configuration below for an example where the graph is especially badly lagging.
```

### Problem-relevant frontend configuration

```yaml
type: entities
entities:
  - entity: sensor.d1_sensors_bme280_temperature
  - entity: sensor.d1_sensors_bme280_dewpoint
  - entity: sensor.d1_sensors_bme280_humidity
  - entity: sensor.d1_sensors_bme280_pressure
title: Dachboden
```

### Javascript errors shown in your browser console/inspector

```txt
None
```

### Additional information

It seems that a lot of animations were either introduced in 2025.1 or they are way slower and they make the web frontend less nice to use, it is not snappy anymore but laggy and you have to wait for seconds before elements have stopped moving around, redrawing and lagging.

### PR DESCRIPTION
**Pull request by MindFreeze**
## Proposed change

This removes a resize action after the dialog is open and instead just sets a fixed height to achieve the same size. All the `resize` methods were only used for this so I removed them.
I don't know if this will entirely fix the slow render issue since I can't reproduce it but it should at least help.

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #23584
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by MindFreeze** [comment]
@karwosts can you try this PR and see if opening a more info dialog with a chart is improved, pls?

**Comment by bramkragten** [comment]
This also removed the initial animation I think? So can we remove the `animation-container` and animation css now too?

**Comment by MindFreeze** [comment]
fixed it to the initial height now

**Comment by bramkragten** [comment]
> fixed it to the initial height now

I think we should move that logic to `ha-chart-base` as that will also use the `clientWidth / 2` if `height` is not set.

File: src/components/chart/statistics-chart.ts [hunk 1]
```diff
@@ -84,8 +84,6 @@ export class StatisticsChart extends LitElement {
 
   @property() public period?: string;
 
-  @property({ attribute: false, type: Number }) public height?: number;
```
Comment (bramkragten) [inline src/components/chart/statistics-chart.ts]: Should we remove the height option completely?

File: src/components/chart/state-history-charts.ts [hunk 2]
```diff
@@ -69,8 +69,6 @@ export class StateHistoryCharts extends LitElement {
 
   @property({ attribute: "fit-y-data", type: Boolean }) public fitYData = false;
 
-  @property({ attribute: false, type: Number }) public height?: number;
```
Comment (bramkragten) [inline src/components/chart/state-history-charts.ts]: Should we remove the height option completely? I think we can keep this?

File: src/components/chart/state-history-chart-line.ts [hunk 3]
```diff
@@ -54,8 +54,6 @@ export class StateHistoryChartLine extends LitElement {
 
   @property({ attribute: "fit-y-data", type: Boolean }) public fitYData = false;
 
-  @property({ attribute: false, type: Number }) public height?: number;
```
Comment (bramkragten) [inline src/components/chart/state-history-chart-line.ts]: Should we remove the height option completely? I think we can keep this?

**Comment by karwosts** [comment]
> @karwosts can you try this PR and see if opening a more info dialog with a chart is improved, pls?

The more info dialog seems better on this branch, but all my energy cards are undesirably huge now (really big bottom padding), and the loading is sometimes really janky. I've never seen anything like this before. 

energy-loading

File: src/components/chart/state-history-chart-line.ts (hunk 3 above)
Comment (MindFreeze) [reply src/components/chart/state-history-chart-line.ts]: It wasn't there before so isn't used. I didn't want to add extra attributes without a use case. We can always add it if we need it.

**Comment by MindFreeze** [comment]
Aha, so this is what `_chartHeight` was for. I added back some of that logic to fix the energy panel

File: src/components/chart/ha-chart-base.ts [hunk 4]
```diff
@@ -471,11 +426,11 @@ export class HaChartBase extends LitElement {
...
-        resize: (chart) => {
-          const change = chart.height - (this._chartHeight ?? 0);
-          if (!this._chartHeight || change > 12 || change < -12) {
-            // hysteresis to prevent infinite render loops
-            this._chartHeight = chart.height;
+        resize: (chart: Chart) => {
+          if (!this.height) {
+            // lock the height
+            // this removes empty space below the chart
+            this.height = chart.height;
```
Comment (bramkragten) [inline src/components/chart/ha-chart-base.ts:433]: We should also add back the hysteresis then?

Comment (MindFreeze) [reply src/components/chart/ha-chart-base.ts:433]: Not needed anymore as we don't animate it. Only lock it once after the first render

**Review by bramkragten — APPROVED** [review]
