### PR TITLE
Fix energy charts with leap years

### LINKED ISSUE #23987: Energy Dashboard shows to small bar graphs while data comparison
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [x] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

After activating data comparison, the width of the bar graphs are wrong.

Core 2025.2.0b2
Supervisor 2025.01.1
Operating System 14.2
Frontend 20250130.0
Image

### Describe the behavior you expected

Correct width of the bars.

### Steps to reproduce the issue

1. Open Energy dashbord
2. Check the data comparison 

### What version of Home Assistant Core has the issue?

2025.2.0b2

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue?

Google Chrome 132.0.6834.112

### Which operating system are you using to run this browser?

Windows 11 Pro

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml

```

### Javascript errors shown in your browser console/inspector

```txt

```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by MindFreeze**
## Proposed change

This is mostly for comparing exactly 1 full year to another or comparing quarters. When using custom ranges, the data is in days and this isn't an issue.

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #23987
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/panels/lovelace/cards/energy/common/energy-chart-options.ts [hunk 1]
```diff
@@ -242,3 +254,21 @@ export function fillDataGapsAndRoundCaps(datasets: BarSeriesOption[]) {
...
   });
 }
+
+export function getCompareTransform(start: Date, compareStart?: Date) {
+  if (!compareStart) {
+    return (ts: Date) => ts;
+  }
+  const compareYearDiff = differenceInYears(start, compareStart);
+  const compareIsYear =
+    compareYearDiff !== 0 && start.getTime() === startOfYear(start).getTime();
```
Comment (bramkragten) [inline src/panels/lovelace/cards/energy/common/energy-chart-options.ts:264]: This only tells us the start is the start of the year, but the period could span multiple years right? Then all of those years would be set to the same year?

**Review by bramkragten — APPROVED** [review]

File: src/panels/lovelace/cards/energy/common/energy-chart-options.ts (hunk 1 above)
Comment (MindFreeze) [reply src/panels/lovelace/cards/energy/common/energy-chart-options.ts]: This was only handling the common case of year comparison. Updated to handle more years or months now. Description updated as well

Comment (bramkragten) [reply src/panels/lovelace/cards/energy/common/energy-chart-options.ts]: Yeah, noticed your changes! Looks good :-)

**Comment by MindFreeze** [comment]
btw If we could properly turn off data snapping for the tooltip, we could use 2 x axis instead of transforming the data but apparently it is too controversial https://github.com/apache/echarts/issues/16675
