### PR TITLE
Fixes #17769, #22503: Improved subscription handling

### LINKED ISSUE #17769: Logbook in "more info dialog" duplicates entries
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When a "more info dialog" with logbook entries is opened on iOS and the app (Safari or HA iOS app) then gets minimized for ~20 seconds, duplicate entries will show up if the app is re-opened.

Here's a video showing the issue (real-time):

https://github.com/home-assistant/frontend/assets/6409465/aca4bb46-7d67-47bf-999e-90c8aff38691

While I'm using the iOS Home Assistant companion app in the video, this also reproduces when just using Safari on iOS.
The iOS version also doesn't seem to matter, since this already happened about a year ago or so.
(Re-opening the more info dialog "removes" the duplicate entries again.)

I'm guessing the duplicate entries appear when the frontend "reconnects" and the list either isn't cleared when doing that, or doesn't check if the to-be-added entries are already present.

(This issue is present since quite some time already, I just finally got around to reporting it.)

### Describe the behavior you expected

New entries should appear upon relaunching the Home Assistant iOS app (or Safari), but duplicate entries shouldn't appear.

### Steps to reproduce the issue

1. Open Home Assistant iOS app or Safari on iOS
2. Open the more info dialog of an entity with a logbook below (for example, a binary sensor)
3. See non-duplicated entries
4. Minimize Home Assistant iOS app (by swiping to home)
5. Wait ~30 seconds
6. Open Home Assistant iOS app again
7. Same more info dialog will still be opened, but now with duplicated logbook entries

(If it doesn't reproduce on first try, minimize the app again, wait a bit (longer), open app again. Doesn't always happen)

### What version of Home Assistant Core has the issue?

core-2023.9.0b1

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

Home Assistant iOS app 2023.4 / also reproduced with just Safari

### Which operating system are you using to run this browser?

iOS 17 Dev Beta 8 / also reproduced on iOS 16.x

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by systemtester**
## Proposed change
- Prevent multiple active subscriptions
- Ensure a clean state when the component reconnects
- Checking subscription status before processing

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: #17769 #22503 
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Review by wendevlin — CHANGES_REQUESTED** [review]

File: src/panels/logbook/ha-logbook.ts [hunk 1]
```diff
@@ -207,32 +207,42 @@ export class HaLogbook extends LitElement {
...
+        }
+      } catch (err: any) {
+        // eslint-disable-next-line
+        console.error("Error unsubscribing:", err);
+      }
     }
   }
 
-  public connectedCallback() {
+  public async connectedCallback() {
```
Comment (wendevlin) [inline src/panels/logbook/ha-logbook.ts:226]:
```suggestion
  public connectedCallback() {
```

File: src/panels/logbook/ha-logbook.ts [hunk 2]
```diff
@@ -207,32 +207,42 @@ export class HaLogbook extends LitElement {
...
     super.connectedCallback();
     if (this.hasUpdated) {
-      this._subscribeLogbookPeriod(this._calculateLogbookPeriod());
+      // Ensure clean state before subscribing
+      await this._subscribeLogbookPeriod(this._calculateLogbookPeriod());
```
Comment (wendevlin) [inline src/panels/logbook/ha-logbook.ts:230]:
```suggestion
      this._subscribeLogbookPeriod(this._calculateLogbookPeriod());
```

it needs to run but we don't need to wait for this.

File: src/panels/logbook/ha-logbook.ts [hunk 3]
```diff
@@ -207,32 +207,42 @@ export class HaLogbook extends LitElement {
...
     }
   }
 
-  public disconnectedCallback() {
+  public async disconnectedCallback() {
```
Comment (wendevlin) [inline src/panels/logbook/ha-logbook.ts:234]:
```suggestion
  public disconnectedCallback() {
```

File: src/panels/logbook/ha-logbook.ts [hunk 4]
```diff
@@ -207,32 +207,42 @@ export class HaLogbook extends LitElement {
...
     super.disconnectedCallback();
-    this._unsubscribeSetLoading();
+    await this._unsubscribeSetLoading();
```
Comment (wendevlin) [inline src/panels/logbook/ha-logbook.ts:236]:
```suggestion
    this._unsubscribeSetLoading();
```

it needs to run but we don't need to wait for this.

**Review by wendevlin — CHANGES_REQUESTED** [review]

**Review by wendevlin — APPROVED** [review]

**Comment by wendevlin** [comment]
Thank you @systemtester
