### PR TITLE
Fix getting custom config parameters for Z-Wave JS

### LINKED ISSUE #52: Values for custom config parameters only show up after reloading the page
During the CTT tests, a device is tested where existing config parameters cannot be determined automatically (Configuration CC V1 or 2).

I pressed <kbd>GET VALUE</kbd> here, the command was sent, but there was not visual feedback.

The highlighted section only showed up after reloading the page:
grafik

This should happen automatically, since it is a certification requirement:
> Verify that the DUT offers a UI which allows the end user to see the parameter numbers which has been set (parameter number = 1) and their current value according to Requirement Number: CL:0070.03.41.01.1

### PR DESCRIPTION
**Pull request by MindFreeze**
## Proposed change

Fix the get request and trigger an config refresh when a a custom parameter number is used.

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes https://github.com/zwave-js/certification-backlog/issues/52
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/panels/config/integrations/integration-panels/zwave_js/zwave_js-node-config.ts [hunk 1]
```diff
@@ -214,6 +214,7 @@ class ZWaveJSNodeConfig extends LitElement {
             <zwave_js-custom-param
               .hass=${this.hass}
               .deviceId=${this.deviceId}
+              .onNewValue=${this._fetchData}
```
Comment (bramkragten) [inline src/panels/config/integrations/integration-panels/zwave_js/zwave_js-node-config.ts:217]: The context of this function will be wrong, also `fetchData` doesn't meet the typing for `onNewValue` set in `zwave_js-custom-param`

File: src/data/zwave_js.ts [hunk 2]
```diff
@@ -715,11 +715,13 @@ export const getZwaveNodeRawConfigParameter = (
   device_id: string,
   property: number
 ): Promise<number> =>
-  hass.callWS({
-    type: "zwave_js/get_raw_config_parameter",
-    device_id,
-    property,
-  });
+  hass
+    .callWS({
```
Comment (bramkragten) [inline src/data/zwave_js.ts:719]:
```suggestion
    .callWS<{value: number}>({
```

File: src/panels/config/integrations/integration-panels/zwave_js/zwave_js-node-config.ts (hunk 1 above)
Comment (bramkragten) [inline src/panels/config/integrations/integration-panels/zwave_js/zwave_js-node-config.ts:217]: You should really use an event here instead of a callback function

**Review by bramkragten — APPROVED** [review]
