### PR TITLE
Make media play button in media browser more visible when hovering

### LINKED ISSUE #23528: Image / Media management - add buttons can sometimes be hard to see
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

The media management dialog where you can select previously uploaded images is a nice addition. But the add button when hovering over the images can sometimes be hard to see, especially in my case because I use a bunch of wireframe images for my area pictures. See the below screen recording for how they blend in:

https://github.com/user-attachments/assets/d4c74c21-c7f6-4bea-8c15-9f5c5ab40092

### Describe the behavior you expected

I think CSS can be tweaked a bit to look more like a FAB where the icon background is filled in rather than transparent. That way the + button never blends in and gets "lost" amongst the image. Here's a quick mockup showing the difference side by side for my hallway area image:

Mockup

### Steps to reproduce the issue

1. Go to a place that has image upload (areas, persons)
2. Instead of dropping an image to upload click the "select from media" link to see existing image uploads
3. Hover over them

### What version of Home Assistant Core has the issue?

2025.1.0b4

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

_No response_

### Which operating system are you using to run this browser?

_No response_

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by jpbede**
## Proposed change
Make the play button in the media browser a bit more visible by reducing the brightness of the image and styling the button itself like a fab. This also fixes the misalignment (was more aligned to the top) of the button 🙂 

| Old | New |
| :-: | :-: |
image | image |

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #23528
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/components/media-player/ha-media-player-browse.ts [hunk 1]
```diff
@@ -1117,6 +1117,11 @@ export class HaMediaPlayerBrowse extends LitElement {
           --mdc-icon-size: 48px;
         }
 
+        ha-card:hover .image {
+          filter: brightness(70%);
+          transition: brightness 0.5s;
```
Comment (wendevlin) [inline src/components/media-player/ha-media-player-browse.ts:1122]:
```suggestion
          transition: filter 0.5s;
```

File: src/components/media-player/ha-media-player-browse.ts [hunk 2]
```diff
@@ -1326,6 +1331,10 @@ export class HaMediaPlayerBrowse extends LitElement {
         ha-browse-media-tts {
           direction: var(--direction);
         }
+        ha-icon-button {
+          background-color: var(--primary-color);
+          color: var(--primary-text-color) !important;
+        }
```
Comment (wendevlin) [inline src/components/media-player/ha-media-player-browse.ts:1337]: replace content of `ha-card:hover .play:not(.can_expand)` with this content, then you don't need the `!important`

**Review by wendevlin — CHANGES_REQUESTED** [review]
Hello Jan-Phillipp,

Thanks for this nice improvement.

I just found some tiny improvements.

**Review by wendevlin — APPROVED** [review]
