### PR TITLE
Fix integrations dialog

### LINKED ISSUE #23252: Can't Add any Integrations in 20241211.0.dev
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When going to devices and trying to add integration the window disappears and no setup options show up. This happens for pihole and others.

### Describe the behavior you expected

I expect to search for integration click it and get a window that is used to set up the specified integration. 

### Steps to reproduce the issue

1. Go to devices and integration
2. add integration

### What version of Home Assistant Core has the issue?

2025.1.0.dev202412110235

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

Both Firefox and Chrome

### Which operating system are you using to run this browser?

Arch Linux

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by MindFreeze**
## Proposed change

Fix the case when a dialog is trying to close itself and then open a new dialog. This happens when adding a new integration

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #23252
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/dialogs/make-dialog-manager.ts [hunk 1]
```diff
@@ -87,15 +87,23 @@ export const showDialog = async (
...
-
-  const { state } = mainWindow.history;
-  // if the same dialog is already open, don't push state
   if (addHistory) {
+    const { history } = mainWindow;
+    if (history.state?.dialog && !OPEN_DIALOG_STACK.length) {
+      // theres is a dialog state in history, but no dialogs open
+      // wait for history.back() to update the state
+      await new Promise((resolve) => {
+        setTimeout(resolve);
```
Comment (bramkragten) [inline src/dialogs/make-dialog-manager.ts:96]: Should we instead call `showDialog` again so we can wait again if needed?

**Review by bramkragten — APPROVED** [review]
