### PR TITLE
Simplify dialog navigation to fix back button

### LINKED ISSUE #14571: Back arrow in settings doesn't play nice with device windows
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The back arrow at the top of every page in the settings works well as long as you don't open any "more info" style pop ups.

For example in the devices page if you click on a device, then on the top left arrow you're brought back to the devices page as expected - great.
But if you click on a device then on any of the sensor to see the graphs, then click out of that and try the back arrow again nothing happens. You have to click it twice to be brought back : once to get 'out' of the pop up which is already gone, and once to get out of the devices.

So it seems the arrow needs to be clicked once for any pop up info you may have seen, which sometimes means tapping on the arrow 10 times to get back. Particularly problematic on phones but also happens on regular desktop browsers.

### Describe the behavior you expected

I'd expect the back arrow to bring me back from the page I'm on, not counting any intermediate pop ups that have already disappeared.
Not sure how this is implemented but I'm guessing dismissing those info pop ups should pop one element out of the history.

### Steps to reproduce the issue

1. Go to any device page
2. Click on a sensor
3. Dismiss the info pop up
4. Try the back arrow

I'm using the devices page as an example but this happens with any page that uses those little window pop up things, whatever they're called. They can be found in integrations configs, by clicking on specific log messages in the viewer ..

### What version of Home Assistant Core has the issue?

2022.11

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

Android app, Firefox Windows, Firefox Linux

### Which operating system are you using to run this browser?

_No response_

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

It's been like that for a very long time, this is not new behavior.
I assumed there would already be a report of this somewhere here but I couldn't find it, apologies if there is already an issue that I missed. Not knowing how any of these elements are called probably isn't helping.

### LINKED ISSUE #17820: Back Button doesn't work
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The back button does not work correctly (yout have to click it 5 times) after opening the more info dialog by clicking the value in an entities card.
If you click on the name or icon, it works. 

image
image

### Describe the behavior you expected

The Back Button should work correctly.

### Steps to reproduce the issue

1. Open a page with a back button 
2. Click on an Value in a entities card
3. Click on the back button 

### What version of Home Assistant Core has the issue?

2023.8.4

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

Edge, Chrome, iOS App, Android App

### Which operating system are you using to run this browser?

Win 11, iOS, Android

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by MindFreeze**
## Proposed change

Removed `replaceDialog` and all related logic as it is not used anywhere. @bramkragten correct me if this is wrong but I couldn't find anything using it.
This allowed me to simplify the history management logic for dialogs and fix back button issues.
Multiple modals on top of each other work well now. `Esc` closes all dialogs but this is managed by the dialogs themselves via the `escapeKeyAction` attribute. An example of this is a siren with advanced options in the `more-info` dialog.

Browser history was too limiting to do what we wanted. Only access to current state, no callbacks in the state, etc. So the dialog states are now managed in a stack inside `make-dialog-manager.ts` and only a single state is pushed to the browser history.
Going forward in history will not open a dialog anymore as it made no sense in most cases.

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #17820 fixes #14571
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by MindFreeze** [comment]
Alright, I think it's in a pretty good state now. Ideally the `urlSyncMixin` shouldn't have anything to do with the dialogs but we still need it to add the `popstate` listener

File: src/dialogs/make-dialog-manager.ts [hunk 1]
```diff
@@ -123,6 +155,42 @@ export const closeDialog = async (dialogTag: string): Promise<boolean> => {
   return true;
 };
 
+// called on back()
+export const closeLastDialog = () => {
+  if (OPEN_DIALOG_STACK.length) {
+    const lastDialog = OPEN_DIALOG_STACK.pop();
+    closeDialog(lastDialog!.dialogTag);
```
Comment (bramkragten) [inline src/dialogs/make-dialog-manager.ts:162]: A dialog can prevent itself from getting closed by a back action, thats why we had:

```js
  const closed = await closeDialog(dialogState.dialog);
  if (!closed) {
    // dialog could not be closed, push state again
    mainWindow.history.pushState(dialogState, "");
  }
```

File: src/state/url-sync-mixin.ts [hunk 2]
```diff
@@ -46,131 +36,32 @@ export const urlSyncMixin = <
...
             }
-            if (state.oldState) {
-              if (DEBUG) {
-                console.log("handle old state");
-              }
-              this._handleDialogStateChange(state.oldState);
+            if ("dialog" in ev.state) {
+              // coming to a dialog
+              // in practice the dialog stack is empty when navigating forward, so this is a no-op
+              showDialogFromHistory(ev.state.dialog);
```
Comment (bramkragten) [inline src/state/url-sync-mixin.ts:63]: It is not really a no-op, as it will trigger a `history.back` (causing the forward button to be enabled again) that will then trigger a `closeLastDialog` which will no-op

**Review by bramkragten — APPROVED** [review]

File: src/state/url-sync-mixin.ts (hunk 2 above)
Comment (MindFreeze) [reply src/state/url-sync-mixin.ts:63]: Yeah, I meant to say nothing will happen from a user perspective but no-op was shorter :D
