### PR TITLE
Fix history Y axis with tiny values

### LINKED ISSUE #24293: History chart rounds values ​​in Y-axis labels
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Before the last update, the history graph labels on the Y axis displayed as many decimal places as the sensor provided. After the last update, the values ​​started rounding in a way that is not intuitive.
One of my sensors has values ​​in the range of 0.001 - 0.01 most of the time. Previously, the Y axis labels had the corresponding values ​​(0.001, 0.002, 0.003 ...). Now the values ​​are displayed as 0, 0, 0, 0, 0.01, 0.01. Accordingly, I have now lost the ability to visually assess the changes in the sensor values ​​over time.
With other sensors that have values ​​> 0, things are not so bad, but still not great.

### Describe the behavior you expected

The accuracy of the values ​​in the Y-axis labels should be calculated based on the spread of the values. If the spread of the values ​​is large, the number of decimal places may be smaller. If the spread of the values ​​is small, the number of decimal places should correspond to the sensor.

### Steps to reproduce the issue

1. Have a sensor that provides >2 decimal places accuracy and a small spread of values.
2. View it in a History Graph or the History viewer.

### What version of Home Assistant Core has the issue?

2025.2.4

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue?

Google Chrome 132.0.6834.197

### Which operating system are you using to run this browser?

Windows 10

### State of relevant entities

```txt
unit_of_measurement: V
device_class: voltage
```

### Problem-relevant frontend configuration

```yaml
type: history-graph
entities:
  - entity: sensor.cell_volt_delta
```

### Javascript errors shown in your browser console/inspector

```txt

```

### Additional information

In the screenshot the sensor takes values ​​in the range of 0.001 - 0.006. On the Y axis it is completely unclear
Image

### PR DESCRIPTION
**Pull request by MindFreeze**
## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #24293
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by karwosts** [comment]
If you had a series of ticks like `[0.11, 0.12, 0.13, 0.14]`, would those just all show as `[0.1, 0.1, 0.1, 0.1]` ?

**Comment by MindFreeze** [comment]
> If you had a series of ticks like `[0.11, 0.12, 0.13, 0.14]`, would those just all show as `[0.1, 0.1, 0.1, 0.1]` ?

That's an edgy case but I guess it could happen. Optimally it would be based on the range instead of the specific value but the range is very dynamic and complicated to determine so I would rather keep it simple.

File: src/components/chart/state-history-chart-line.ts [hunk 1]
```diff
@@ -256,7 +256,21 @@ export class StateHistoryChartLine extends LitElement {
...
+                      maximumFractionDigits: Math.max(
+                        2,
+                        -Math.floor(Math.log10(Math.abs(value % 1 || 1)))
+                      ),
+                    };
+              const label = formatNumber(
+                value,
+                this.hass.locale,
+                formatOptions
+              );
```
Comment (piitaya) [inline src/components/chart/state-history-chart-line.ts:273]: Why don't we use the display precision from the entity registry for this one?

Comment (MindFreeze) [reply src/components/chart/state-history-chart-line.ts:273]: There could be many entities. Even if it is only 1, it doesn't make sense to show axis labels that are all the same like is shown in the issue

**Review by bramkragten — APPROVED** [review]
We should check if we can get the min and max and base it on that but for now 👍
