### PR TITLE
Fix Markdown cards in Grid not taking full height

### LINKED ISSUE #23119: Markdown cards in grid card are not taking full height
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Starting with Core 2024.8.0, Markdown cards contained in Grid cards do not take the same height as the neighboring button. It doesn't happen if the cards are in a horizontal stack (bottom):
image

### Describe the behavior you expected

Cards will be rendered as in Core < 2024.8.0:
image

### Steps to reproduce the issue

Create a Grid card containing Markdown cards:
```
type: grid
cards:
  - type: markdown
    content: ' '
  - show_name: true
    show_icon: true
    type: button
    tap_action:
      action: toggle
    entity: zone.home
  - type: markdown
    content: ' '
```

### What version of Home Assistant Core has the issue?

2024.8.0+

### What was the last working version of Home Assistant Core?

2024.7.3

### In which browser are you experiencing the issue with?

Firefox 132.0.2 (64-bit)

### Which operating system are you using to run this browser?

Arch Linux

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by sairon**
## Proposed change

The implementation of show_empty property in #21379 introduced regression which causes Markdown cards rendered within a Grid card to not take full height of its space. This is because a visible card is now forced to have "display: block", while without that it's rendered as "display: inline".

As the CSSStyleDeclaration.style mandates string type, it's not possible to delete or null the value. Setting it to an empty string seems to do the trick as well and the linter is happy too.

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml
type: grid
cards:
  - type: markdown
    content: ' '
  - show_name: true
    show_icon: true
    type: button
    tap_action:
      action: toggle
    entity: zone.home
  - type: markdown
    content: ' '

```

## Additional information

- This PR fixes or closes issue: fixes #23119
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/panels/lovelace/cards/hui-markdown-card.ts [hunk 1]
```diff
@@ -111,7 +111,7 @@ export class HuiMarkdownCard extends LitElement implements LovelaceCard {
       this._config.show_empty === false &&
       this._templateResult.result.length === 0;
     if (shouldBeHidden !== this.hidden) {
-      this.style.display = shouldBeHidden ? "none" : "block";
+      this.style.display = shouldBeHidden ? "none" : "";
       this.toggleAttribute("hidden", shouldBeHidden);
```
Comment (sairon) [inline src/panels/lovelace/cards/hui-markdown-card.ts:115]: Removing the line setting the `display` property would IMO work too, as the HTML `hidden` attribute is toggled as well. Is there a reason to do both?

Comment (piitaya) [reply src/panels/lovelace/cards/hui-markdown-card.ts:115]: hidden is use by the parent (grid card) to know if it's hidden or not so it can ignore it. The display css property is used to not display the element. (Semantic vs styling, we need both)

**Review by piitaya — APPROVED** [review]
Thank you
